# Generated by Django 4.1.5 on 2023-01-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
    ]
