# Generated by Django 4.1.5 on 2023-01-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Table',
        ),
    ]
